Added  Automatically Updated contributors section using github action and also added CODE_OF_CONDUCT
makoteq/metaxa pull request #35
Opened 2022-10-30 18:30 UTC by sb-decoder

@makoteq please check this PR and if you want this changes in your repo then merge this. Thank You.

2022-10-30 22:20 UTC, makoteq commented
Hi! @sb-decoder 
Interesting idea,
Could you make a new section for contributors and put "contrib rocks" img in it?
I think that would make it look better
After that im willing to merge this one

2022-10-31 04:21 UTC, sb-decoder commented
> Hi! @sb-decoder Interesting idea, Could you make a new section for contributors and put "contrib rocks" img in it? I think that would make it look better After that im willing to merge this one

@makoteq  I have made a PR , please check if your query solved or not.

2022-10-31 10:41 UTC, sb-decoder commented
@makoteq Please check this one.

2022-10-31 11:51 UTC, makoteq requested changes

2022-10-31 11:51 UTC, makoteq commented on README.md
> +## ✨ Contributors
Fix typo, link doesnt work

2022-10-31 12:49 UTC, sb-decoder commented on README.md
> +## ✨ Contributors
After merge , the link will work finely

2022-10-31 12:50 UTC, sb-decoder commented
@makoteq resolved issue

2022-10-31 12:57 UTC, makoteq requested changes

2022-10-31 12:57 UTC, makoteq commented on README.md
> +Chcekout our [Contributors](https://github.com/makoteq/metaxa/blob/master/CONTRIBUTORS.md)
fix `Chcekout ` typo

2022-10-31 12:58 UTC, makoteq commented on README.md
> +Chcekout our [Contributors](https://github.com/makoteq/metaxa/blob/master/CONTRIBUTORS.md)
and link still doesnt work!

2022-10-31 13:00 UTC, makoteq commented
Please test your changes before submitting

2022-10-31 13:01 UTC, sb-decoder commented
> Please test your changes before submitting

I fixed typo mistake and link will start working after you merge it.

2022-10-31 13:03 UTC, sb-decoder commented
Link is not working now because you still have not the CONTRIBUTORS.md in your repo. So it can't find it.

2022-10-31 14:06 UTC, merged

2022-10-31 14:06 UTC, makoteq commented
good work!